"""todennäköisyys-kenttä

Revision ID: 63abadb6da8e
Revises: bf5953d93e7d
Create Date: 2020-04-26 21:31:06.878356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63abadb6da8e'
down_revision = 'bf5953d93e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liidit', sa.Column('todennakoisyys', sa.Numeric(precision=2, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liidit', 'todennakoisyys')
    # ### end Alembic commands ###
